services:
  django:
    build: django
    restart: unless-stopped
    environment:
      DJANGO_SECRET_FILE: /run/secrets/django
      DJANGO_ALLOWED_HOST: catpowered.net
    secrets:
    - django
    volumes:
    - type: bind
      source: ./data/django
      target: /opt/www/data
      bind:
        create_host_path: true

secrets:
  django:
    file: secrets/django.yml
