services:
  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: --config /run/secrets/cloudflared tunnel run
    secrets:
    - cloudflared
  django:
    build: django
    restart: unless-stopped
    environment:
      DJANGO_SECRET_FILE: /run/secrets/django
      DJANGO_ALLOWED_HOST: catpowered.net
    secrets:
    - django
    volumes:
    - type: bind
      source: ./data/django
      target: /opt/www/data
      bind:
        create_host_path: true
  finger:
    build: https://github.com/Maronato/go-finger.git
    volumes:
    - type: bind
      source: ./data/fingers.yml
      target: /app/fingers.yml
      bind:
        create_host_path: false

secrets:
  cloudflared:
    file: secrets/cloudflared.yml
  django:
    file: secrets/django.yml
